# defaultAirflowTag: "2.3.0"

images:
  airflow:
    repository: apache/airflow
    tag: latest
    pullPolicy: IfNotPresent
  statsd:
    repository: cachengo/airflow-statsd-exporter
    tag: latest
    pullPolicy: IfNotPresent
  pgbouncer:
    repository: cachengo/pgbouncer
    tag: latest
  pgbouncerExporter:
    repository: cachengo/airflow-pgbouncer-exporter
    tag: latest
  # flower: 
  #   repository: apache/airflow
  #   tag: latest
  gitSync:
    repository: thockin/git-sync
    tag: v3.1.6-dirty__linux_arm64
    pullPolicy: IfNotPresent

flower:
  enabled: false

data:
  metadataConnection:
    user: postgres
    pass: password
    host: postgres-service-airflow

postgresql:
  enabled: false

pgbouncer:
  enabled: true

workers:
  resources:
    limits:
      cpu: 100m
      memory: 128 Mi
    requests:
      cpu: 100m
      memory: 128Mi

scheduler:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

webserver:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

dags:
  persistence:
    enabled: false
    storageClassName: longhorn
  gitSync:
    enabled: false
    repo: ssh://git@github.com/cachengo/Airflow-Dags
    branch: main
    subPath: ""

# logs:
#   peresistance:
#     enabled: true 