# defaultAirflowTag: "2.3.0"

images:
  # airflow:
  #   repository: apache/airflow
  #   tag: latest
  #   pullPolicy: IfNotPresent
  statsd:
    repository: cachengo/airflow-statsd-exporter
    tag: latest
    pullPolicy: IfNotPresent
  pgbouncer:
    repository: cachengo/pgbouncer
    tag: latest
  pgbouncerExporter:
    repository: cachengo/airflow-pgbouncer-exporter
    tag: latest
  # flower: 
  #   repository: apache/airflow
  #   tag: latest
  gitSync:
    repository: thockin/git-sync
    tag: v3.1.6-dirty__linux_arm64
    pullPolicy: IfNotPresent

flower:
  enabled: false

data:
  metadataConnection:
    user: Y2l0dXN1c2Vy
    pass: Y2l0dXNwYXNzd29yZA==
    host: postgres-service.default

postgresql:
  enabled: false

dags:
  persistence:
    enabled: false
    storageClassName: longhorn
  gitSync:
    enabled: false
    repo: ssh://git@github.com/cachengo/Airflow-Dags
    branch: main
    subPath: ""